name: flutter_movie_app
description: A complete Flutter Movie App with API, Hive, and Riverpod.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.3.2
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  go_router: ^12.1.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true